### PR TITLE
Longest increasing subsequence

### PR DESCRIPTION
**Pull request by athulsukumaran**

### CODE REVIEW

**Review by roshinjojuc — APPROVED** [review]
This is good.

The approach tries to find the largest increasing sequence starting from number at index i I think.
I saw an another approach in the discuss section and some video where in the dp array we store the length of largest increasing sequence ending at number at index i.

Do check that one also.

**Comment by athulsukumaran** [comment]
> This is good.
> 
> The approach tries to find the largest increasing sequence starting from number at index i I think. I saw an another approach in the discuss section and some video where in the dp array we store the length of largest increasing sequence ending at number at index i.
> 
> Do check that one also.

Any change in either of the complexities with this approach?

**Comment by roshinjojuc** [comment]
> > This is good.
> > The approach tries to find the largest increasing sequence starting from number at index i I think. I saw an another approach in the discuss section and some video where in the dp array we store the length of largest increasing sequence ending at number at index i.
> > Do check that one also.
> 
> Any change in either of the complexities with this approach?

Complexity wise, they are similar.

Also My Bad. We are updating the LIS dp Array at J. So this is also storing the length of longest increasing sub sequence that ends at number at index J. I thought we were updating the LIS dp Array at I in inner loop.

The other approach seemed intuitive.

**Comment by roshinjojuc** [comment]
> > > This is good.
> > > The approach tries to find the largest increasing sequence starting from number at index i I think. I saw an another approach in the discuss section and some video where in the dp array we store the length of largest increasing sequence ending at number at index i.
> > > Do check that one also.
> > 
> > 
> > Any change in either of the complexities with this approach?
> 
> Complexity wise, they are similar.
> 
> Also My Bad. We are updating the LIS dp Array at J. So this is also storing the length of longest increasing sub sequence that ends at number at index J. I thought we were updating the LIS dp Array at I in inner loop.
> 
> The other approach seemed intuitive.

Geeks for Geeks

https://www.youtube.com/watch?v=Ns4LCeeOFS4

**Pull request merged**
